---
- hosts: localhost
  tasks:
    - digital_ocean:
        state: present
        command: droplet
        name: mydroplet
        api_token: <DO API Token> 
        size_id: 2gb
        region_id: ams3
        image_id: ubuntu-16-04-x64
        wait_timeout: 500
        ssh_pub_key: '<Your SSH public key>'
      register: my_droplet
    
    - debug:
        msg: "ID is {{ my_droplet.droplet.id }}"
    
    - debug:
        msg: "IP is {{ my_droplet.droplet.ip_address }}"


